/// Model representing a company in the industrial monitoring system.
/// Each company has multiple machines and production facilities.
class Company {
  final String id;
  final String name;
  final String industry;
  final String location;
  final int totalMachines;

  /// True if the server received machine telemetry within the last 15 minutes.
  final bool isOnline;

  /// Date of the most recent production_history record for this client.
  final DateTime? lastSeenDate;

  final String? latestDowntimeReason;
  final String? latestDowntimeDescription;

  const Company({
    required this.id,
    required this.name,
    required this.industry,
    required this.location,
    required this.totalMachines,
    this.isOnline = false,
    this.lastSeenDate,
    this.latestDowntimeReason,
    this.latestDowntimeDescription,
  });

  @override
  String toString() => name;
}

/// Represents the operational status of a machine.
enum MachineStatus { running, stopped, maintenance }

/// Model representing an industrial machine.
/// Contains operational data like cycle counts, downtime, and status.
class Machine {
  final String id;
  final String name;
  final String type;
  final String companyId;
  final MachineStatus status;
  final int cycleCount;
  final double cureCycleTime; // in minutes
  final int downtimeMinutes;
  final int startCount;
  final int stopCount;
  final DateTime lastMaintenance;
  final double temperature;
  final double efficiency; // percentage

  /// Live motor current in Amperes (null if no sensor).
  final double? motorCurrent;

  /// Live motor speed in RPM (null if no sensor).
  final double? motorSpeedRpm;

  /// True when admin has disabled this machine for this client.
  /// Client UI must not allow enabling it.
  final bool adminDisabled;

  /// True when VFD fault is active on this machine.
  final bool vfdFault;

  /// Live running bit from PLC (null if not available).
  final bool? runBit;

  const Machine({
    required this.id,
    required this.name,
    required this.type,
    required this.companyId,
    required this.status,
    required this.cycleCount,
    required this.cureCycleTime,
    required this.downtimeMinutes,
    required this.startCount,
    required this.stopCount,
    required this.lastMaintenance,
    required this.temperature,
    required this.efficiency,
    this.motorCurrent,
    this.motorSpeedRpm,
    this.adminDisabled = false,
    this.vfdFault = false,
    this.runBit,
  });

  /// Combined start+stop count for backward compat
  int get startStopCount => startCount + stopCount;

  /// Check if machine is currently running
  bool get isRunning => status == MachineStatus.running;

  /// Check if downtime is critically high (over 60 minutes)
  bool get hasHighDowntime => downtimeMinutes > 60;

  /// Get status color indicator
  String get statusLabel {
    switch (status) {
      case MachineStatus.running:
        return 'Running';
      case MachineStatus.stopped:
        return 'Stopped';
      case MachineStatus.maintenance:
        return 'Maintenance';
    }
  }
}

/// Severity levels for alerts in the monitoring system.
enum AlertSeverity { low, medium, high, critical }

/// Types of alerts that can be generated by the system.
enum AlertType {
  machineStopped,
  highDowntime,
  temperatureWarning,
  maintenanceDue,
  productionTargetMissed,
  abnormalCondition,
  lowEfficiency,
  emergencyTriggered,
  vfdFault,
  hydraulicPressureLow,
  controlOff,
  machineStop,
  materialLow,
  hydraulicOff,
  programStop,
}

/// Model representing an alert/notification in the system.
/// Alerts are generated when abnormal conditions are detected.
class Alert {
  final String id;
  final String companyId;
  final String machineId;
  final String machineName;
  final AlertType type;
  final AlertSeverity severity;
  final String message;
  final DateTime timestamp;
  final bool isRead;
  final bool isResolved;

  const Alert({
    required this.id,
    required this.companyId,
    required this.machineId,
    required this.machineName,
    required this.type,
    required this.severity,
    required this.message,
    required this.timestamp,
    this.isRead = false,
    this.isResolved = false,
  });

  /// Get human-readable alert type name
  String get typeName {
    switch (type) {
      case AlertType.machineStopped:
        return 'Machine Stopped';
      case AlertType.highDowntime:
        return 'High Downtime';
      case AlertType.temperatureWarning:
        return 'Temperature Warning';
      case AlertType.maintenanceDue:
        return 'Maintenance Due';
      case AlertType.productionTargetMissed:
        return 'Production Target Missed';
      case AlertType.abnormalCondition:
        return 'Abnormal Condition';
      case AlertType.lowEfficiency:
        return 'Low Efficiency';
      case AlertType.emergencyTriggered:
        return 'Emergency Triggered';
      case AlertType.vfdFault:
        return 'VFD Fault';
      case AlertType.hydraulicPressureLow:
        return 'Hydraulic Pressure Low';
      case AlertType.controlOff:
        return 'Control Off';
      case AlertType.machineStop:
        return 'Machine Stop';
      case AlertType.materialLow:
        return 'Material Low';
      case AlertType.hydraulicOff:
        return 'Hydraulic Off';
      case AlertType.programStop:
        return 'Program Stop';
    }
  }

  /// Get severity label
  String get severityLabel {
    switch (severity) {
      case AlertSeverity.low:
        return 'Low';
      case AlertSeverity.medium:
        return 'Medium';
      case AlertSeverity.high:
        return 'High';
      case AlertSeverity.critical:
        return 'Critical';
    }
  }

  /// Create a copy with updated properties
  Alert copyWith({bool? isRead, bool? isResolved}) {
    return Alert(
      id: id,
      companyId: companyId,
      machineId: machineId,
      machineName: machineName,
      type: type,
      severity: severity,
      message: message,
      timestamp: timestamp,
      isRead: isRead ?? this.isRead,
      isResolved: isResolved ?? this.isResolved,
    );
  }
}

/// Model for a raw PLC tag value.
class RawTag {
  final String key;
  final String label;
  final dynamic value;
  final String unit;

  const RawTag({
    required this.key,
    required this.label,
    required this.value,
    required this.unit,
  });
}

/// Represents a single historical hourly energy point.
class EnergyHistoryPoint {
  final double hour;
  final double kwh;
  final double amps;
  final double pf;

  const EnergyHistoryPoint({
    required this.hour,
    required this.kwh,
    required this.amps,
    required this.pf,
  });

  factory EnergyHistoryPoint.fromJson(Map<String, dynamic> j) {
    return EnergyHistoryPoint(
      hour: (j['hour'] as num? ?? 0.0).toDouble(),
      kwh: (j['energy_kwh'] as num? ?? 0.0).toDouble(),
      amps: (j['overall_amps'] as num? ?? 0.0).toDouble(),
      pf: (j['power_factor'] as num? ?? 0.0).toDouble(),
    );
  }
}

/// Live energy / power meter data from the PLC power analyser.
class EnergyData {
  final double amps;        // Overall amps
  final double kwh;         // Total energy kWh
  final double hz;          // Frequency Hz
  final double pf;          // Overall power factor
  final double voltageAvg;  // Phase-to-neutral avg V
  final double llAvg;       // Line-to-line avg V
  // Phase voltages
  final double l1;
  final double l2;
  final double l3;
  final double l12;
  final double l23;
  final double l31;
  // Phase currents
  final double l1Amps;
  final double l2Amps;
  final double l3Amps;
  // Phase power factors
  final double l1Pf;
  final double l2Pf;
  final double l3Pf;
  // Computed
  final double overallPowerKw;

  const EnergyData({
    this.amps = 0, this.kwh = 0, this.hz = 0, this.pf = 0,
    this.voltageAvg = 0, this.llAvg = 0,
    this.l1 = 0, this.l2 = 0, this.l3 = 0,
    this.l12 = 0, this.l23 = 0, this.l31 = 0,
    this.l1Amps = 0, this.l2Amps = 0, this.l3Amps = 0,
    this.l1Pf = 0, this.l2Pf = 0, this.l3Pf = 0,
    this.overallPowerKw = 0,
  });

  static EnergyData fromJson(Map<String, dynamic> j) => EnergyData(
    amps:          (j['amps']          as num? ?? 0).toDouble(),
    kwh:           (j['kwh']           as num? ?? 0).toDouble(),
    hz:            (j['hz']            as num? ?? 0).toDouble(),
    pf:            (j['pf']            as num? ?? 0).toDouble(),
    voltageAvg:    (j['voltageAvg']    as num? ?? 0).toDouble(),
    llAvg:         (j['llAvg']         as num? ?? 0).toDouble(),
    l1:            (j['l1']            as num? ?? 0).toDouble(),
    l2:            (j['l2']            as num? ?? 0).toDouble(),
    l3:            (j['l3']            as num? ?? 0).toDouble(),
    l12:           (j['l12']           as num? ?? 0).toDouble(),
    l23:           (j['l23']           as num? ?? 0).toDouble(),
    l31:           (j['l31']           as num? ?? 0).toDouble(),
    l1Amps:        (j['l1Amps']        as num? ?? 0).toDouble(),
    l2Amps:        (j['l2Amps']        as num? ?? 0).toDouble(),
    l3Amps:        (j['l3Amps']        as num? ?? 0).toDouble(),
    l1Pf:          (j['l1Pf']          as num? ?? 0).toDouble(),
    l2Pf:          (j['l2Pf']          as num? ?? 0).toDouble(),
    l3Pf:          (j['l3Pf']          as num? ?? 0).toDouble(),
    overallPowerKw:(j['overallPowerKw'] as num? ?? 0).toDouble(),
  );
}

/// Model for holding production statistics over different time periods.
class ProductionStats {
  final String companyId;
  final double dailyProduction;
  final double weeklyProduction;
  final double monthlyProduction;
  final double yearlyProduction;
  final int totalCycles;
  final int todayCycles;
  final double averageCureCycleTime;
  final int currentCycleTimeMs;
  final int lastCycleTimeMs;
  final String activeRecipeName;
  final String blockName;
  final int actualCount;
  final int targetCount;
  final Map<String, dynamic> hourlyBreakdown;
  final int concurrentCalls;
  final int totalDowntimeMinutes;
  final int machinesRunning;
  final int machinesStopped;
  final int machinesInMaintenance;
  final double overallEfficiency;
  final DateTime lastUpdated;
  final List<RawTag> rawTags;

  // ── Live energy data ──────────────────────────────────────────────────
  final EnergyData energy;

  // ── Historical energy data ────────────────────────────────────────────
  final List<EnergyHistoryPoint> todayEnergyHistory;
  final List<EnergyHistoryPoint> yesterdayEnergyHistory;

  const ProductionStats({
    required this.companyId,
    required this.dailyProduction,
    required this.weeklyProduction,
    required this.monthlyProduction,
    required this.yearlyProduction,
    required this.totalCycles,
    required this.todayCycles,
    required this.averageCureCycleTime,
    required this.currentCycleTimeMs,
    required this.lastCycleTimeMs,
    required this.activeRecipeName,
    required this.blockName,
    required this.actualCount,
    required this.targetCount,
    required this.hourlyBreakdown,
    required this.concurrentCalls,
    required this.totalDowntimeMinutes,
    required this.machinesRunning,
    required this.machinesStopped,
    required this.machinesInMaintenance,
    required this.overallEfficiency,
    required this.lastUpdated,
    required this.rawTags,
    this.energy = const EnergyData(),
    this.todayEnergyHistory = const [],
    this.yesterdayEnergyHistory = const [],
  });

  /// Total number of machines
  int get totalMachines =>
      machinesRunning + machinesStopped + machinesInMaintenance;

  /// Total start+stop combined (deprecated)
  int get totalStartStops => actualCount;

  /// Format downtime as hours and minutes
  String get formattedDowntime {
    final hours = totalDowntimeMinutes ~/ 60;
    final minutes = totalDowntimeMinutes % 60;
    if (hours > 0) {
      return '${hours}h ${minutes}m';
    }
    return '${minutes}m';
  }
}

/// Model for detailed report data within a date range.
class ReportData {
  final String companyId;
  final String companyName;
  final DateTime startDate;
  final DateTime endDate;
  final List<DailyProductionRecord> dailyRecords;
  final double totalProduction;
  final double averageEfficiency;
  final int totalDowntimeMinutes;
  final int totalCycles;

  const ReportData({
    required this.companyId,
    required this.companyName,
    required this.startDate,
    required this.endDate,
    required this.dailyRecords,
    required this.totalProduction,
    required this.averageEfficiency,
    required this.totalDowntimeMinutes,
    required this.totalCycles,
  });

  ReportData copyWith({
    String? companyId,
    String? companyName,
    DateTime? startDate,
    DateTime? endDate,
    List<DailyProductionRecord>? dailyRecords,
    double? totalProduction,
    double? averageEfficiency,
    int? totalDowntimeMinutes,
    int? totalCycles,
  }) {
    return ReportData(
      companyId: companyId ?? this.companyId,
      companyName: companyName ?? this.companyName,
      startDate: startDate ?? this.startDate,
      endDate: endDate ?? this.endDate,
      dailyRecords: dailyRecords ?? this.dailyRecords,
      totalProduction: totalProduction ?? this.totalProduction,
      averageEfficiency: averageEfficiency ?? this.averageEfficiency,
      totalDowntimeMinutes: totalDowntimeMinutes ?? this.totalDowntimeMinutes,
      totalCycles: totalCycles ?? this.totalCycles,
    );
  }
}


/// Daily production record for reports.
class DailyProductionRecord {
  final DateTime date;
  final double production;
  final int cycles;
  final int blockCount;
  final int downtimeMinutes;
  final double efficiency;
  final int activeMachines;
  final Map<String, dynamic> hourlyBreakdown;

  const DailyProductionRecord({
    required this.date,
    required this.production,
    required this.cycles,
    required this.blockCount,
    required this.downtimeMinutes,
    required this.efficiency,
    required this.activeMachines,
    required this.hourlyBreakdown,
  });
}

/// Model for SIM recharge information displayed in the Profile screen.
class SimRechargeInfo {
  final DateTime lastRechargeDate;
  final DateTime planValidity;
  final int remainingDays;

  const SimRechargeInfo({
    required this.lastRechargeDate,
    required this.planValidity,
    required this.remainingDays,
  });
}

/// Model for user information displayed in the Profile screen.
class UserInfo {
  final String name;
  final String role;

  const UserInfo({
    required this.name,
    required this.role,
  });
}

/// Model for company profile information displayed in the Profile screen.
class CompanyProfileInfo {
  final String name;
  final String location;
  final int totalMachines;

  const CompanyProfileInfo({
    required this.name,
    required this.location,
    required this.totalMachines,
  });
}

/// Model for usage statistics displayed in the Profile screen.
class UsageStats {
  final int totalAlerts;
  final int monthlyDowntimeMinutes;
  final double efficiencyPercent;

  const UsageStats({
    required this.totalAlerts,
    required this.monthlyDowntimeMinutes,
    required this.efficiencyPercent,
  });

  String get formattedMonthlyDowntime {
    final hours = monthlyDowntimeMinutes ~/ 60;
    final minutes = monthlyDowntimeMinutes % 60;
    if (hours > 0) {
      return '${hours}h ${minutes}m';
    }
    return '${minutes}m';
  }
}

/// Model that bundles all profile-related data for a company.
class ProfileData {
  final UserInfo userInfo;
  final CompanyProfileInfo companyInfo;
  final SimRechargeInfo simInfo;
  final UsageStats usageStats;

  const ProfileData({
    required this.userInfo,
    required this.companyInfo,
    required this.simInfo,
    required this.usageStats,
  });
}

/// Enum for support ticket status.
enum TicketStatus { open, acknowledged, resolved }

/// Model for a support ticket.
class SupportTicket {
  final int id;
  final String clientId;
  final String clientName;
  final String title;
  final String description;
  final TicketStatus status;
  final DateTime createdAt;
  final DateTime? acknowledgedAt;
  final DateTime? resolvedAt;

  const SupportTicket({
    required this.id,
    required this.clientId,
    required this.clientName,
    required this.title,
    required this.description,
    required this.status,
    required this.createdAt,
    this.acknowledgedAt,
    this.resolvedAt,
  });

  factory SupportTicket.fromJson(Map<String, dynamic> json) {
    return SupportTicket(
      id: json['id'],
      clientId: json['client_id'] ?? '',
      clientName: json['client_name'] ?? 'Unknown Client',
      title: json['title'] ?? '',
      description: json['description'] ?? '',
      status: _parseStatus(json['status']),
      createdAt: DateTime.parse(json['created_at']),
      acknowledgedAt: json['acknowledged_at'] != null ? DateTime.parse(json['acknowledged_at']) : null,
      resolvedAt: json['resolved_at'] != null ? DateTime.parse(json['resolved_at']) : null,
    );
  }

  static TicketStatus _parseStatus(String? s) {
    if (s == 'acknowledged') return TicketStatus.acknowledged;
    if (s == 'resolved') return TicketStatus.resolved;
    return TicketStatus.open;
  }

  String get statusLabel {
    switch (status) {
      case TicketStatus.open: return 'Open';
      case TicketStatus.acknowledged: return 'In Progress';
      case TicketStatus.resolved: return 'Resolved';
    }
  }

  bool get isOpen => status == TicketStatus.open;
  bool get isAcknowledged => status == TicketStatus.acknowledged;
  bool get isResolved => status == TicketStatus.resolved;

  Duration? get resolutionTime {
    if (acknowledgedAt != null && resolvedAt != null) {
      return resolvedAt!.difference(acknowledgedAt!);
    }
    return null;
  }

  Duration get age {
    return DateTime.now().difference(createdAt);
  }

  Duration? get workDuration {
    if (acknowledgedAt == null) return null;
    final end = resolvedAt ?? DateTime.now();
    return end.difference(acknowledgedAt!);
  }
}
